name: Deploy to Amazon EKS

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install EKS Auth Plugin
      run: |
        curl -o aws-iam-authenticator \
        https://amazon-eks.s3.us-west-2.amazonaws.com/1.29.0/2024-04-19/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        sudo mv aws-iam-authenticator /usr/local/bin/

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker images
      run: |
        ECR="${{ secrets.ECR_REGISTRY }}"
        for svc in src/* ; do
          if [ -f "$svc/Dockerfile" ]; then
            NAME=$(basename $svc)
            docker build -t $ECR/online-boutique/$NAME:latest $svc
            docker push $ECR/online-boutique/$NAME:latest
          fi
        done

    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name devops-eks \
          --role-arn ${{ secrets.AWS_ROLE_ARN }}

    - name: Verify cluster access
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: kubectl get nodes

    - name: Deploy to EKS
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: kubectl apply -f k8s-manifests/ --validate=false

